
//
// Created by dev on 2020/3/10.
//

#ifndef MULTI_THREADED_MULTI_FILE_BREAKPOINT_RESUME_DOWNLOAD_CONSTANT_H
#define MULTI_THREADED_MULTI_FILE_BREAKPOINT_RESUME_DOWNLOAD_CONSTANT_H

const int DOWNLOAD_NOT_START = -1;
const int DOWNLOAD_ING = -0;
const int DOWNLOAD_FINISH = 1;

#endif // MULTI_THREADED_MULTI_FILE_BREAKPOINT_RESUME_DOWNLOAD_CONSTANT_H
